import Css from "./css.svg"
import Csv from "./csv.svg"
import Excel from "./excel.svg"
import File from "./file.svg"
import Html from "./html.svg"
import Jpg from "./jpg.svg"
import Mov from "./mov.svg"
import Mp3 from "./mp3.svg"
import Pdf from "./pdf.svg"
import Png from "./png.svg"
import Rar from "./rar.svg"
import Text from "./text.svg"
import Undefind from "./undefined.svg"
import Wav from "./wav.svg"
import Word from "./word.svg"
import Zip from "./zip.svg"

export default {Css, Csv, Excel, File, Html, Jpg, Mov, Mp3, Pdf, Png, Rar, Text, Undefind, Wav, Word, Zip}